path:
  assetfolder: D:/research/dataset/.objaverse/hf-objaverse-v1
  metadriveasset: E:/bolei/MetaVQA/metadrive/assets/models/test
  metadriveassetgltf: D:/research/dataset/pede
  parentfolder: E:/bolei/VQAAsset
  raw_assetfolder: D:/research/dataset/raw_asset_folder
  subfolders:
    adj_parameter_folder: adj_parameter_folder
    all_tag_path: all_tag_list.json
    filter_asset_path_folder: filter_asset_path_folder
    ignore_adj_folder: ignore_adj_folder
    layout_static_info_folder: layout_static_info_folder
    match_uid_path_folder: match_uid_path_folder
    raw_asset_path_folder: raw_asset_path_folder