---
storage_path : "/bigdata/weizhen/metavqa_iclr/scenarios/test_wide"
sample_frequency: 2
num_samples: 100
max_iterations: 1000000000000000
temporal_generation: True
episode_length: 10
skip_length: 5
...